name: "Terraform Action Lab Provision Workflow"
on:
    push:
        branches: 
            - 'main'
    pull_request:
        branches:
            - 'main'
concurrency:
    group: ${{ github.head_ref || github.ref }}

permissions:
    id-token: write
    contents: read
    pull-requests: write

env:
    TF_LOG: INFO
    #AWS_REGION: ${{ vars.AWS_REGION }}
    #AWS_ROLE: ${{ secrets.AWS_ROLE }}
    ROLE_SESSION: Github-OIDC-TERRAFORM-development

jobs:
    development-plan:
        concurrency:
            group: ${{ github.base_ref }}-development_environment
            cancel-in-progress: false
        runs-on: ubuntu-latest
        environment: development
        if: github.event_name == 'pull_request'
        steps:
            - name: checkout
              uses: actions/checkout@v4
            
            - name: Configure AWS credentials from AWS account
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: ${{ vars.AWS_REGION }}
                #role-to-assume: ${{ secrets.AWS_ROLE }}
                #role-session-name: ${{ env.ROLE_SESSION }}
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: development-plan
              uses: Cloud-Engineering-EA/composite-action-terraform-deploy@v1.6
              with:
                config_directory: terraform
                terraform_action: plan
                environment: development
    development-apply:
        concurrency:
            group: ${{ github.base_ref }}-development
            cancel-in-progress: false
        runs-on: ubuntu-latest
        environment: development
        if: github.event_name == 'push'
        steps:
            - name: checkout
              uses: actions/checkout@v4
            
            - name: Configure AWS credentials from AWS account
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: ${{ vars.AWS_REGION }}
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: development-apply
              uses: Cloud-Engineering-EA/composite-action-terraform-deploy@v1.6
              with:
                config_directory: terraform
                terraform_action: apply
                environment: development
    staging-plan:
        concurrency:
            group: ${{ github.base_ref }}-staging_environment
            cancel-in-progress: false
        runs-on: ubuntu-latest
        environment: staging
        if: github.base_ref == 'main' && github.event_name == 'pull_request'
        steps:
            - name: checkout
              uses: actions/checkout@v4
            
            - name: Configure AWS credentials from AWS account
              uses: aws-actions/configure-aws-credentials@v4
              with:
                aws-region: ${{ vars.AWS_REGION }}
                aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

            - name: staging-plan
              uses: Cloud-Engineering-EA/composite-action-terraform-deploy@v1.6
              with:
                config_directory: terraform
                terraform_action: plan
                environment: staging







